name: 'Set up node'
description: 'Composite action to set up node'
runs:
  using: 'composite'
  steps:
    - name: Set up node
      uses: actions/setup-node@v3
      with:
        node-version-file: 'package.json'

    - name: Restore yarn cache
      uses: actions/cache@v3
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: .yarn/cache
        key: ${{ runner.os }}-yarn-${{ github.head_ref || github.ref}}-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-${{ github.head_ref || github.ref}}-
          ${{ runner.os }}-yarn-

    - name: Install project dependencies
      shell: bash
      run: yarn install --immutable
