name: Node.js CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up node
        uses: ./.github/actions/setup-node

      - name: Restore jest cache
        uses: actions/cache@v3
        id: jest-cache
        with:
          path: jestCache
          key: ${{ runner.os }}-jest-${{ github.head_ref || github.ref }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-jest-${{ github.head_ref || github.ref }}-
            ${{ runner.os }}-jest-

      - run: yarn jest --ci --colors
